# Generated by Django 3.2.18 on 2023-04-29 10:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Etablissement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_inscription', models.BigIntegerField()),
                ('birth_date', models.DateField()),
                ('phone_number', models.CharField(max_length=50)),
                ('profile_picture', models.ImageField(upload_to='project/images')),
                ('filiére', models.CharField(max_length=255)),
                ('spécialité', models.CharField(max_length=100)),
                ('etablissement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.etablissement')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user__first_name', 'user__last_name'],
            },
        ),
    ]
