# Generated by Django 3.2.18 on 2023-04-29 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_auto_20230429_1229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etablissement',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
