# Generated by Django 3.2.18 on 2023-04-29 14:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project', '0003_alter_etablissement_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_inscription', models.BigIntegerField(blank=True, null=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=50, null=True)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='project/images')),
                ('grade', models.CharField(choices=[('Professeur', 'Professeur'), ('Maître de conférences A', 'Maître de conférences A'), ('Maître de conférences B', 'Maître de conférences B'), ('Maître assistant A', 'Maître assistant A'), ('Maître assistant B', 'Maître assistant B')], max_length=255)),
                ('spécialité', models.CharField(blank=True, max_length=100, null=True)),
                ('etablissement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='project.etablissement')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user__first_name', 'user__last_name'],
            },
        ),
    ]
