# Generated by Django 3.2.18 on 2023-04-29 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='etablissement',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='project/images'),
        ),
    ]
