# Generated by Django 3.2.18 on 2023-04-30 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_etablissement_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManagementTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('période de soumission des projets', 'période de soumission des projets'), ('période de validation des projet', 'période de validation des projet'), ('période de dépôt des recours', 'période de dépôt des recours'), ('période da validation des projets aprés recours', 'période da validation des projets aprés recours')], max_length=255)),
                ('description', models.TextField(blank=True)),
                ('date_début', models.DateField()),
                ('date_fin', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='ProjectInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('invitation de participation pour la supervision', 'invitation de participation pour la supervision'), ('invitation de participation dans une équipe de projet', 'invitation de participation dans une équipe de projet')], max_length=255)),
                ('description', models.TextField(blank=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('un diplôme - une startup', 'un diplôme - une startup'), ('Un diplôme - Un Brevet', 'Un diplôme - Un Brevet')], help_text='Select the type of the project', max_length=50)),
                ('intitulé_idée_innovante', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('members', models.ManyToManyField(to='project.ProjectInvitation')),
                ('participants', models.ManyToManyField(blank=True, to='project.Student')),
                ('team_leader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chef_équipe', to='project.student')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled'), ('On Hold', 'On Hold'), ('Rejected', 'Rejected')], default='On Hold', max_length=50)),
                ('deposition_date', models.DateField(auto_now_add=True)),
                ('résumé', models.TextField(blank=True)),
                ('period', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='project.period')),
                ('porteur_student', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='project.student')),
                ('porteur_teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='project.teacher')),
                ('project_team', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='équipe_projet', to='project.projectteam')),
                ('project_type', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='project.projecttype')),
                ('équipe_encadrement', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='équipe_encadrement', to='project.managementteam')),
                ('établissement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.etablissement')),
            ],
        ),
        migrations.AddField(
            model_name='managementteam',
            name='co_superviseur',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='co_superviseur', to='project.projectinvitation'),
        ),
        migrations.AddField(
            model_name='managementteam',
            name='superviseur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='superviseur', to='project.teacher'),
        ),
    ]
