# Generated by Django 3.2.18 on 2023-04-30 17:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_auto_20230430_1549'),
    ]

    operations = [
        migrations.CreateModel(
            name='DecisionOfCommitte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('Avis favorable', 'Avis favorable'), ('Accepté sous réserves', 'Accepté sous réserves'), ('Avis défavorable', 'Avis défavorable')], max_length=255)),
                ('réserves_mineurs', models.BooleanField(default=False, help_text='Si le projet est dans les réserves mineurs', verbose_name='Réserves mineures')),
                ('réserves_majeures', models.BooleanField(default=False, help_text='Si le projet est dans les réserves majeures', verbose_name='Réserves majeures')),
            ],
        ),
        migrations.AddField(
            model_name='teacher',
            name='is_membre_of_commité',
            field=models.BooleanField(default=False, help_text='Si cet enseignant est un membre dans une comité', verbose_name='Membre de la commité ?'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='is_president_of_commité',
            field=models.BooleanField(default=False, help_text='Si cet enseignant est un présidant dans une comité', verbose_name="Présidant de l'incubateur ?"),
        ),
        migrations.CreateModel(
            name='ValidationCommittee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('membres', models.ManyToManyField(to='project.Teacher')),
                ('établissement', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='project.etablissement')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectValidation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remarques', models.TextField(blank=True)),
                ('validation_date', models.DateField(auto_now=True)),
                ('committee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='project_validation_committe', to='project.validationcommittee')),
                ('decision', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='project_decision', to='project.decisionofcommitte')),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='project_to_validate', to='project.project')),
            ],
        ),
    ]
