# Generated by Django 3.2.18 on 2023-04-30 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_auto_20230430_1853'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DecisionOfCommitte',
            new_name='DecisionOfCommittee',
        ),
        migrations.RemoveField(
            model_name='validationcommittee',
            name='name',
        ),
    ]
