# Generated by Django 3.2.18 on 2023-04-30 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0008_auto_20230430_1903'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='etablissement',
            new_name='établissement',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='num_inscription',
            new_name='matricule',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='etablissement',
            new_name='établissement',
        ),
    ]
