# Generated by Django 3.2.18 on 2023-04-30 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0009_auto_20230430_1914'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='decisionofcommittee',
            name='réserves_majeures',
        ),
        migrations.RemoveField(
            model_name='decisionofcommittee',
            name='réserves_mineurs',
        ),
        migrations.AddField(
            model_name='decisionofcommittee',
            name='decription',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='decisionofcommittee',
            name='title',
            field=models.CharField(choices=[('Avis favorable', 'Avis favorable'), ('Accepté sous réserves mineurs', 'Accepté sous réserves mineurs'), ('Accepté sous réserves majeures', 'Accepté sous réserves majeurs'), ('Avis défavorable', 'Avis défavorable')], max_length=255),
        ),
    ]
