# Generated by Django 3.2.18 on 2023-04-30 19:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0010_auto_20230430_1926'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('date_deposition', models.DateTimeField(auto_now=True)),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='period_recours', to='project.period')),
            ],
        ),
        migrations.CreateModel(
            name='RecoursValidation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='project.projectvalidation')),
                ('recours', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='project.recours')),
            ],
        ),
    ]
