# Generated by Django 3.2.18 on 2023-04-30 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0011_recours_recoursvalidation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recoursvalidation',
            old_name='project',
            new_name='validated_project',
        ),
    ]
