# Generated by Django 3.2.18 on 2023-04-30 22:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0012_rename_project_recoursvalidation_validated_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='project.period'),
        ),
    ]
