# Generated by Django 3.2.18 on 2023-05-02 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0015_alter_projectvalidation_decision'),
    ]

    operations = [
        migrations.RenameField(
            model_name='decisionofcommittee',
            old_name='decription',
            new_name='description',
        ),
    ]
