# Generated by Django 3.2.19 on 2023-05-10 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0017_rename_membres_validationcommittee_members'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='équipe_encadrement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='équipe_encadrement', to='project.managementteam'),
        ),
    ]
