# Generated by Django 3.2.19 on 2023-05-13 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0018_alter_project_équipe_encadrement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectteam',
            name='members',
        ),
        migrations.AlterField(
            model_name='managementteam',
            name='co_superviseur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='co_superviseur', to='project.teacher'),
        ),
    ]
