# Generated by Django 3.2.19 on 2023-05-14 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0019_auto_20230513_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='managementteam',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
