# Generated by Django 3.2.19 on 2023-05-17 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0021_auto_20230516_1831'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectinvitation',
            name='consumed',
            field=models.BooleanField(default=False),
        ),
    ]
