# Generated by Django 3.2.19 on 2023-05-18 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0023_alter_projectinvitation_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectteam',
            name='team_leader',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='chef_équipe', to='project.student'),
        ),
    ]
