# Generated by Django 3.2.19 on 2023-06-03 23:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0024_alter_projectteam_team_leader'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectteam',
            name='team_leader',
        ),
        migrations.AlterField(
            model_name='managementteam',
            name='superviseur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='superviseur', to='project.teacher'),
        ),
    ]
